version: '3'
services:
  elasticsearch:
    image: elasticsearch:alpine
    ports:
      - "9100:9200"
    environment:
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"

  logstash:
    image: logstash:5
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
    links:
      - elasticsearch:elasticsearch
      - redis:redis

  kibana:
    image: kibana:5
    volumes:
      - ./kibana/config/:/etc/kibana/
    ports:
      - "5601:5601"
    links:
      - elasticsearch:elasticsearch

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
